### ISSUE TITLE
jogamp missing

### ISSUE THREAD

**Issue by tischi** [HenriquesLab/SReD#3]
Hi, 

I downloaded the latest jar following the instructions in the README but trying to run it I am getting:

```
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 213MB of 10987MB (1%)
 
java.lang.NoClassDefFoundError: com/jogamp/opencl/CLException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
```

Using Apple M2...

**Comment by ammendes** [comment]
Hi @tischi ! Sorry for the inconvenience.

Please let me know the following to help solve the issue:
1. Did you download SReD from the Github page or did you use the "ImageJ Update Site"?
2. Do you also have the eSRRF plugin in ImageJ?

**Comment by tischi** [comment]
I followed the instructions for [installing from github releases](https://github.com/HenriquesLab/SReD?tab=readme-ov-file#installing-from-github-releases), i.e. I downloaded the jar and placed it in Fiji.

**Comment by ammendes** [comment]
Can you please install eSRRF in ImageJ, restart ImageJ and then run SReD again? 

You can do it in "Update..." > "Manage Update Sites" and add the eSRRF website (https://sites.imagej.net/NanoJ-LiveSRRF/).

**Comment by paxcalpt** [comment]
Hi @ammendes, 

We should change the section of the readme @tischi mentions to reflect that there are needed dependencies, or remove that first section about installing by copying the jar and just ask users to use the repos.

Thank you @tischi for highlighting this.

**Comment by tischi** [comment]
Running it when installing both update sites is working. Maybe indeed just remove the other option.

**Comment by ammendes** [comment]
Thanks @tischi ! We'll remove the other option for now, until we sort it out.

**Comment by jkh1** [comment]
Maybe this isn't fixed. I followed the installation instructions (i.e. installing via update site) then when I try SReD > Relevance Mask > Calculate Relevance Mask (2D), I get
- in the console: `Couln't load native CL/JNI glue library`
- in the Exception window: 
```
(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_172 [64-bit]; Linux 5.4.0-182-generic; 1216MB of 20876MB (5%)
 
com.jogamp.common.JogampRuntimeException: JOCL is not available
	at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:171)
	at com.jogamp.opencl.CLPlatform.initialize(CLPlatform.java:147)
	at com.jogamp.opencl.CLPlatform.listCLPlatforms(CLPlatform.java:220)
	at com.jogamp.opencl.CLPlatform.listCLPlatforms(CLPlatform.java:211)
	at OptimiseRelevanceMask_.run(OptimiseRelevanceMask_.java:136)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ammendes** [comment]
@jkh1 did you also install eSRRF?

**Comment by jkh1** [comment]
Yes I followed the instructions [here](https://github.com/HenriquesLab/SReD#installation)

**Comment by ammendes** [comment]
Sorry about that. I reopened the issue.
@jkh1 you have a different error message, which is related to a problem with Linux compatibility, but I believe the solution we're working on will solve both issues.
As a temporary workaround, you can try using a Windows or MacOS machine if you have one available, it should work.
If you try that, please let me know how it went.

**Comment by ammendes** [comment]
Hi @tischi and @jkh1. 
We updated the ImageJ update site. The issue should now be resolved.

Please try the following:
- Either start from a clean Fiji install, or simply uncheck the SReD and eSRRF update sites to uninstall the plugins, then restart Fiji.
- Go to the update sites again and check the SReD site to install the new version. No need to check eSRRF from now on. 
- Restart Fiji and then try the plugin. 

please let me know how that went.

**Comment by jkh1** [comment]
@ammendes  I can confirm that it's now fixed for me on Linux.
